// generated by newgenasym  Thu May 28 16:40:44 2020


module \evp-aaxxxx  (\1 , \2 , \3 , \4 , \5 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;
    inout \5 ;


    initial
        begin
        end

endmodule
