-- generated by newgenasym Thu May 28 16:40:44 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \evp-aaxxxx\ is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC);
end \evp-aaxxxx\;
