// generated by newgenasym  Thu Feb 13 17:03:07 2020


module mx25u51245g_54 (\cs# , ep, gnd, sclk, \si/sio0 , sio2, sio3, \so/sio1 , vcc);
    input \cs# ;
    input ep;
    input gnd;
    input sclk;
    inout \si/sio0 ;
    input sio2;
    input sio3;
    inout \so/sio1 ;
    input vcc;


    initial
        begin
        end

endmodule
