-- generated by newgenasym Thu Feb 13 17:03:07 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mx25u51245g_54 is
    port (    
	\cs#\:     IN     STD_LOGIC;    
	EP:        IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	SCLK:      IN     STD_LOGIC;    
	\si/sio0\: INOUT  STD_LOGIC;    
	SIO2:      IN     STD_LOGIC;    
	SIO3:      IN     STD_LOGIC;    
	\so/sio1\: INOUT  STD_LOGIC;    
	VCC:       IN     STD_LOGIC);
end mx25u51245g_54;
