// generated by newgenasym  Thu Nov  5 00:42:48 2020


module xtal (\/st , \1 , \2 , \3 , \4 , gnd, gnd1, gnd2, gnd_1, gnd_2, \i.c._1 , \i.c._2 ,
        nc, nc1, nc2, nc_1, nc_2, oe, out, p1, p2, p3, stby, vcc, vcon,
        vdd, vio);
    output \/st ;
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;
    input gnd;
    input gnd1;
    output gnd2;
    input gnd_1;
    input gnd_2;
    inout \i.c._1 ;
    inout \i.c._2 ;
    inout nc;
    inout nc1;
    inout nc2;
    inout nc_1;
    inout nc_2;
    input oe;
    output out;
    input p1;
    output p2;
    inout p3;
    input stby;
    input vcc;
    input vcon;
    input vdd;
    input vio;


    initial
        begin
        end

endmodule
