-- generated by newgenasym Thu Nov  5 00:42:48 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity xtal is
    port (    
	\/st\:     OUT    STD_LOGIC;    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	GND1:      IN     STD_LOGIC;    
	GND2:      OUT    STD_LOGIC;    
	GND_1:     IN     STD_LOGIC;    
	GND_2:     IN     STD_LOGIC;    
	\i.c._1\:  INOUT  STD_LOGIC;    
	\i.c._2\:  INOUT  STD_LOGIC;    
	NC:        INOUT  STD_LOGIC;    
	NC1:       INOUT  STD_LOGIC;    
	NC2:       INOUT  STD_LOGIC;    
	NC_1:      INOUT  STD_LOGIC;    
	NC_2:      INOUT  STD_LOGIC;    
	OE:        IN     STD_LOGIC;    
	\out\:     OUT    STD_LOGIC;    
	P1:        IN     STD_LOGIC;    
	P2:        OUT    STD_LOGIC;    
	P3:        INOUT  STD_LOGIC;    
	STBY:      IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	VCON:      IN     STD_LOGIC;    
	VDD:       IN     STD_LOGIC;    
	VIO:       IN     STD_LOGIC);
end xtal;
