// generated by newgenasym  Tue Apr 14 13:54:51 2020


module res_smd (\1 , \2 , \3 , tab);
    inout \1 ;
    inout \2 ;
    inout \3 ;
    input tab;


    initial
        begin
        end

endmodule
