-- generated by newgenasym Tue Apr 14 13:54:51 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity res_smd is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	TAB:       IN     STD_LOGIC);
end res_smd;
