-- generated by newgenasym Mon Feb 17 16:32:26 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ek_cap_np is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end ek_cap_np;
