-- generated by newgenasym Tue Aug 11 11:52:35 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \tf13ba-6s\ is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC);
end \tf13ba-6s\;
