// generated by newgenasym  Thu Jul  9 15:35:44 2020


module lis2ds12 (cs, gnd_1, gnd_2, int1, int2, nc, res, \scl/spc , \sda/sdi/sdo ,
        \sdo/sa0 , vdd, vddio);
    inout cs;
    input gnd_1;
    input gnd_2;
    input int1;
    input int2;
    inout nc;
    input res;
    inout \scl/spc ;
    inout \sda/sdi/sdo ;
    inout \sdo/sa0 ;
    input vdd;
    input vddio;


    initial
        begin
        end

endmodule
