-- generated by newgenasym Thu Jul  9 15:35:44 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lis2ds12 is
    port (    
	CS:        INOUT  STD_LOGIC;    
	GND_1:     IN     STD_LOGIC;    
	GND_2:     IN     STD_LOGIC;    
	INT1:      IN     STD_LOGIC;    
	INT2:      IN     STD_LOGIC;    
	NC:        INOUT  STD_LOGIC;    
	RES:       IN     STD_LOGIC;    
	\scl/spc\: INOUT  STD_LOGIC;    
	\sda/sdi/sdo\: INOUT  STD_LOGIC;    
	\sdo/sa0\: INOUT  STD_LOGIC;    
	VDD:       IN     STD_LOGIC;    
	VDDIO:     IN     STD_LOGIC);
end lis2ds12;
