// generated by newgenasym  Tue Feb 24 19:02:29 2015


module max3207 (gnd, \i/o_1 , \i/o_2 , nc1, nc2, vcc);
    input gnd;
    inout \i/o_1 ;
    inout \i/o_2 ;
    inout nc1;
    inout nc2;
    input vcc;


    initial
        begin
        end

endmodule
