-- generated by newgenasym Tue Feb 24 19:02:29 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity max3207 is
    port (    
	GND:       IN     STD_LOGIC;    
	\i/o_1\:   INOUT  STD_LOGIC;    
	\i/o_2\:   INOUT  STD_LOGIC;    
	NC1:       INOUT  STD_LOGIC;    
	NC2:       INOUT  STD_LOGIC;    
	VCC:       IN     STD_LOGIC);
end max3207;
