-- generated by newgenasym Fri May 15 01:07:54 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity thermistor_smd is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\1_1\:     INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end thermistor_smd;
