// generated by newgenasym  Fri Feb 08 13:55:33 2019


module max14689 (cb, com1, com2, ep, gnd, gnd_1, gnd_2, nc1, nc2, no1, no2, vcc);
    input cb;
    input com1;
    input com2;
    input ep;
    input gnd;
    input gnd_1;
    inout gnd_2;
    inout nc1;
    inout nc2;
    inout no1;
    inout no2;
    input vcc;


    initial
        begin
        end

endmodule
