-- generated by newgenasym Fri Feb 08 13:55:33 2019

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity max14689 is
    port (    
	CB:        IN     STD_LOGIC;    
	COM1:      IN     STD_LOGIC;    
	COM2:      IN     STD_LOGIC;    
	EP:        IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	GND_1:     IN     STD_LOGIC;    
	GND_2:     INOUT  STD_LOGIC;    
	NC1:       INOUT  STD_LOGIC;    
	NC2:       INOUT  STD_LOGIC;    
	NO1:       INOUT  STD_LOGIC;    
	NO2:       INOUT  STD_LOGIC;    
	VCC:       IN     STD_LOGIC);
end max14689;
