-- generated by newgenasym Fri May 15 16:37:06 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \fh26-25s\ is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\10\:      INOUT  STD_LOGIC;    
	\11\:      INOUT  STD_LOGIC;    
	\12\:      INOUT  STD_LOGIC;    
	\13\:      INOUT  STD_LOGIC;    
	\14\:      INOUT  STD_LOGIC;    
	\15\:      INOUT  STD_LOGIC;    
	\16\:      INOUT  STD_LOGIC;    
	\17\:      INOUT  STD_LOGIC;    
	\18\:      INOUT  STD_LOGIC;    
	\19\:      INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\20\:      INOUT  STD_LOGIC;    
	\21\:      INOUT  STD_LOGIC;    
	\22\:      INOUT  STD_LOGIC;    
	\23\:      INOUT  STD_LOGIC;    
	\24\:      INOUT  STD_LOGIC;    
	\25\:      INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC;    
	\7\:       INOUT  STD_LOGIC;    
	\8\:       INOUT  STD_LOGIC;    
	\9\:       INOUT  STD_LOGIC);
end \fh26-25s\;
