-- generated by newgenasym Fri Jun 19 12:28:43 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ferritebead is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end ferritebead;
