-- generated by newgenasym Fri Oct 16 06:18:05 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ek_res_smd is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\1_l\:     INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end ek_res_smd;
