-- generated by newgenasym Fri Jul 29 17:11:52 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity evkit_tp is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	TP1:       INOUT  STD_LOGIC);
end evkit_tp;
