// generated by newgenasym  Mon Nov 04 10:34:16 2019


module induct (\1 , \2 , \3 , \4 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;


    initial
        begin
        end

endmodule
