-- generated by newgenasym Mon Nov 04 10:34:16 2019

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity induct is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC);
end induct;
