// generated by newgenasym  Mon Aug 01 17:16:56 2016


module dx07s024jj3 (a1, a10, a11, a12, a2, a3, a4, a5, a6, a7, a8, a9, b1, b10, b11,
        b12, b2, b3, b4, b5, b6, b7, b8, b9, shield_1, shield_2,
        shield_3, shield_4);
    inout a1;
    inout a10;
    inout a11;
    inout a12;
    inout a2;
    inout a3;
    inout a4;
    inout a5;
    inout a6;
    inout a7;
    inout a8;
    inout a9;
    inout b1;
    inout b10;
    inout b11;
    inout b12;
    inout b2;
    inout b3;
    inout b4;
    inout b5;
    inout b6;
    inout b7;
    inout b8;
    inout b9;
    inout shield_1;
    inout shield_2;
    inout shield_3;
    inout shield_4;


    initial
        begin
        end

endmodule
