// generated by newgenasym  Tue Aug 23 16:54:13 2016


module max9062 (gnd, in, out, vcc);
    input gnd;
    input in;
    output out;
    input vcc;


    initial
        begin
        end

endmodule
