-- generated by newgenasym Tue Aug 23 16:54:13 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity max9062 is
    port (    
	GND:       IN     STD_LOGIC;    
	\in\:      IN     STD_LOGIC;    
	\out\:     OUT    STD_LOGIC;    
	VCC:       IN     STD_LOGIC);
end max9062;
