// generated by newgenasym  Tue May 19 10:05:05 2020


module antenna (\1 , \1_1 , \2 , \2_1 , feed, feed_1, feed_2, gnd_1, gnd_2, gnd_3,
        gnd_4, gnd_5, nc_1, nc_2, nc_3, nc_4, nc_5, stud_1, stud_2,
        stud_3);
    inout \1 ;
    inout \1_1 ;
    inout \2 ;
    inout \2_1 ;
    inout feed;
    inout feed_1;
    inout feed_2;
    input gnd_1;
    input gnd_2;
    input gnd_3;
    inout gnd_4;
    inout gnd_5;
    inout nc_1;
    inout nc_2;
    inout nc_3;
    inout nc_4;
    inout nc_5;
    input stud_1;
    input stud_2;
    input stud_3;


    initial
        begin
        end

endmodule
