-- generated by newgenasym Tue May 19 10:05:05 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity antenna is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\1_1\:     INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\2_1\:     INOUT  STD_LOGIC;    
	FEED:      INOUT  STD_LOGIC;    
	FEED_1:    INOUT  STD_LOGIC;    
	FEED_2:    INOUT  STD_LOGIC;    
	GND_1:     IN     STD_LOGIC;    
	GND_2:     IN     STD_LOGIC;    
	GND_3:     IN     STD_LOGIC;    
	GND_4:     INOUT  STD_LOGIC;    
	GND_5:     INOUT  STD_LOGIC;    
	NC_1:      INOUT  STD_LOGIC;    
	NC_2:      INOUT  STD_LOGIC;    
	NC_3:      INOUT  STD_LOGIC;    
	NC_4:      INOUT  STD_LOGIC;    
	NC_5:      INOUT  STD_LOGIC;    
	STUD_1:    IN     STD_LOGIC;    
	STUD_2:    IN     STD_LOGIC;    
	STUD_3:    IN     STD_LOGIC);
end antenna;
