// generated by newgenasym  Tue Feb 11 14:37:37 2020


module max32666 (\32kin , \32kout , ant, ant_thru, dm, \dnc-1 , \dnc-2 , dp, gnd,
        hfxin, hfxout, lxa, lxb, nc, \p0.0 , \p0.1 , \p0.10 , \p0.11 , \p0.12 ,
        \p0.13 , \p0.14 , \p0.15 , \p0.16 , \p0.17 , \p0.18 , \p0.19 , \p0.2 , \p0.20 ,
        \p0.21 , \p0.22 , \p0.23 , \p0.24 , \p0.25 , \p0.26 , \p0.27 , \p0.28 , \p0.29 ,
        \p0.3 , \p0.30 , \p0.31 , \p0.4 , \p0.5 , \p0.6 , \p0.7 , \p0.8 , \p0.9 , \p1.0_1 ,
        \p1.0_2 , \p1.1 , \p1.10 , \p1.11 , \p1.12 , \p1.13 , \p1.14 , \p1.15 , \p1.2 ,
        \p1.3 , \p1.4 , \p1.5 , \p1.6 , \p1.7 , \p1.8 , \p1.9 , rstn, swclk, swdio,
        vbst, vcorea_1, vcorea_2, vcorea_3, vcoreb_1, vcoreb_2,
        vcoreb_3, vdd_bt1, \vdd_bt1-1 , vdd_bt2, vdd_bt3, vdd_bt4,
        vdd_bt5, vdda, vddb, vddio_1, vddio_2, vddio_3, vddio_4,
        vddioh_1, vddioh_2, vddioh_3, vregi_1, vregi_2, vrego_a,
        vrego_b, vrego_c, vrego_d, vrxin, vrxout, vss, \vss-1 , \vss-2 ,
        \vss-3 , \vss-4 , vss_1, vss_2, vss_3, vss_4, vss_5, vss_6, vssa,
        vssa_bt0, \vssa_bt0-1 , \vssa_bt0-2 , vssa_bt1, \vssa_bt1-1 ,
        vssa_bt2, vssa_bt3, vssa_bt4, vssa_bt5, vssb, vsspwr_1,
        vsspwr_2, vtxin, vtxout);
    input \32kin ;
    output \32kout ;
    input ant;
    output ant_thru;
    input dm;
    inout \dnc-1 ;
    inout \dnc-2 ;
    inout dp;
    input gnd;
    input hfxin;
    output hfxout;
    input lxa;
    input lxb;
    inout nc;
    inout \p0.0 ;
    inout \p0.1 ;
    inout \p0.10 ;
    inout \p0.11 ;
    inout \p0.12 ;
    inout \p0.13 ;
    inout \p0.14 ;
    inout \p0.15 ;
    inout \p0.16 ;
    inout \p0.17 ;
    inout \p0.18 ;
    inout \p0.19 ;
    inout \p0.2 ;
    inout \p0.20 ;
    inout \p0.21 ;
    inout \p0.22 ;
    inout \p0.23 ;
    inout \p0.24 ;
    inout \p0.25 ;
    inout \p0.26 ;
    inout \p0.27 ;
    inout \p0.28 ;
    inout \p0.29 ;
    inout \p0.3 ;
    inout \p0.30 ;
    inout \p0.31 ;
    inout \p0.4 ;
    inout \p0.5 ;
    inout \p0.6 ;
    inout \p0.7 ;
    inout \p0.8 ;
    inout \p0.9 ;
    inout \p1.0_1 ;
    inout \p1.0_2 ;
    inout \p1.1 ;
    inout \p1.10 ;
    inout \p1.11 ;
    inout \p1.12 ;
    inout \p1.13 ;
    inout \p1.14 ;
    inout \p1.15 ;
    inout \p1.2 ;
    inout \p1.3 ;
    inout \p1.4 ;
    inout \p1.5 ;
    inout \p1.6 ;
    inout \p1.7 ;
    inout \p1.8 ;
    inout \p1.9 ;
    input rstn;
    input swclk;
    input swdio;
    input vbst;
    input vcorea_1;
    input vcorea_2;
    input vcorea_3;
    input vcoreb_1;
    input vcoreb_2;
    input vcoreb_3;
    input vdd_bt1;
    input \vdd_bt1-1 ;
    input vdd_bt2;
    input vdd_bt3;
    input vdd_bt4;
    input vdd_bt5;
    input vdda;
    input vddb;
    input vddio_1;
    input vddio_2;
    input vddio_3;
    input vddio_4;
    input vddioh_1;
    input vddioh_2;
    input vddioh_3;
    input vregi_1;
    input vregi_2;
    input vrego_a;
    input vrego_b;
    input vrego_c;
    input vrego_d;
    input vrxin;
    output vrxout;
    input vss;
    input \vss-1 ;
    input \vss-2 ;
    input \vss-3 ;
    input \vss-4 ;
    input vss_1;
    input vss_2;
    input vss_3;
    input vss_4;
    input vss_5;
    input vss_6;
    input vssa;
    input vssa_bt0;
    input \vssa_bt0-1 ;
    input \vssa_bt0-2 ;
    input vssa_bt1;
    input \vssa_bt1-1 ;
    input vssa_bt2;
    input vssa_bt3;
    input vssa_bt4;
    input vssa_bt5;
    input vssb;
    input vsspwr_1;
    input vsspwr_2;
    input vtxin;
    output vtxout;


    initial
        begin
        end

endmodule
