// generated by newgenasym  Mon Feb 17 18:16:03 2020


module led_4p (a, a1, a2, a3, a_1, b1, b2, k, k1, \k1-b , k2, \k2-g , k3, \k3-r , k_1,
        kb, kg, kr);
    inout a;
    inout a1;
    inout a2;
    inout a3;
    inout a_1;
    inout b1;
    inout b2;
    inout k;
    inout k1;
    inout \k1-b ;
    inout k2;
    inout \k2-g ;
    inout k3;
    inout \k3-r ;
    inout k_1;
    inout kb;
    inout kg;
    inout kr;


    initial
        begin
        end

endmodule
