-- generated by newgenasym Mon Feb 17 18:16:03 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity led_4p is
    port (    
	A:         INOUT  STD_LOGIC;    
	A1:        INOUT  STD_LOGIC;    
	A2:        INOUT  STD_LOGIC;    
	A3:        INOUT  STD_LOGIC;    
	A_1:       INOUT  STD_LOGIC;    
	B1:        INOUT  STD_LOGIC;    
	B2:        INOUT  STD_LOGIC;    
	K:         INOUT  STD_LOGIC;    
	K1:        INOUT  STD_LOGIC;    
	\k1-b\:    INOUT  STD_LOGIC;    
	K2:        INOUT  STD_LOGIC;    
	\k2-g\:    INOUT  STD_LOGIC;    
	K3:        INOUT  STD_LOGIC;    
	\k3-r\:    INOUT  STD_LOGIC;    
	K_1:       INOUT  STD_LOGIC;    
	KB:        INOUT  STD_LOGIC;    
	KG:        INOUT  STD_LOGIC;    
	KR:        INOUT  STD_LOGIC);
end led_4p;
