// generated by newgenasym  Wed Jul 22 16:01:51 2020


module ek_max32670 (a1, a2, a3, a4, a5, a6, b1, b2, b3, b4, b5, b6, c1, c2, c3, c4, c5,
        c6, d1, d2, d3, d4, d5, d6);
    inout a1;
    inout a2;
    inout a3;
    inout a4;
    inout a5;
    inout a6;
    inout b1;
    inout b2;
    inout b3;
    inout b4;
    inout b5;
    inout b6;
    inout c1;
    inout c2;
    inout c3;
    inout c4;
    inout c5;
    inout c6;
    inout d1;
    inout d2;
    inout d3;
    inout d4;
    inout d5;
    inout d6;


    initial
        begin
        end

endmodule
