// generated by newgenasym  Sat Feb  8 00:43:47 2020


module max4737 (com1, com2, com3, com4, gnd, in1, in2, in3, in4, no1, no2, no3,
        no4, \v+ );
    input com1;
    input com2;
    input com3;
    input com4;
    input gnd;
    input in1;
    input in2;
    input in3;
    input in4;
    output no1;
    output no2;
    output no3;
    output no4;
    input \v+ ;


    initial
        begin
        end

endmodule
