-- generated by newgenasym Sat Feb  8 00:43:47 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity max4737 is
    port (    
	COM1:      IN     STD_LOGIC;    
	COM2:      IN     STD_LOGIC;    
	COM3:      IN     STD_LOGIC;    
	COM4:      IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	IN1:       IN     STD_LOGIC;    
	IN2:       IN     STD_LOGIC;    
	IN3:       IN     STD_LOGIC;    
	IN4:       IN     STD_LOGIC;    
	NO1:       OUT    STD_LOGIC;    
	NO2:       OUT    STD_LOGIC;    
	NO3:       OUT    STD_LOGIC;    
	NO4:       OUT    STD_LOGIC;    
	\v+\:      IN     STD_LOGIC);
end max4737;
