// generated by newgenasym  Thu May 28 17:54:09 2020


module \434153017835  (\1 , \2 , \3 , \4 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;


    initial
        begin
        end

endmodule
