-- generated by newgenasym Thu May 28 17:54:09 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \434153017835\ is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC);
end \434153017835\;
